### PR TITLE
Added some changes

### PR DESCRIPTION
**Pull request by 1asso**
These scripts work fine on assignment1-test with Python 3.9.1.

- change "master" to "all" because many repos don't use master branch.
- added .gitignore file(.DS_Store is for MacOS users).

### CODE REVIEW

**Review by snadi — COMMENTED** [review]
This looks good to me. Can you also:

- Update the readme file with new python version
- create a requirements file with exact dependency versions this works with and update instructions to install these dependencies?

Basically, just to ensure everyone can use these

**Comment by snadi** [comment]
@1asso, also note Issue #1 .. does the API work correctly for you with python 3?

**Comment by 1asso** [comment]
> @1asso, also note Issue #1 .. does the API work correctly for you with python 3?

it works fine, and I checked the document, it has such method:

Screen Shot 2021-01-07 at 3 13 20 PM

**Review by snadi — APPROVED** [review]
Perfect. Thank you!

**Pull request merged**
